[build]
builder = "RAILPACK"
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
preDeployCommand = "python manage.py migrate --noinput"
startCommand = "gunicorn config.wsgi --bind 0.0.0.0:$PORT"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
